name: Deploy to GH-Pages

on:
  push:
    branches:
      - master
    # paths:
    #   - email-subscribe/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
         working-directory: email-subscribe

      - name: Build project - Email Subscribe
        run: npm --prefix email-subscribe run build

      - name: Upload build files
        uses: actions/upload-artifact@v2
        with:
          name: prod-files
          path: ./email-subscribe/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download Build artifacts
        uses: actions/download-artifact@v2
        with:
          name: prod-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.DEPLOY_KEY}}
          publish_dir: ./dist
          external_repository: Thwani47/thwani47.github.io
          publish_branch: master
          destination_dir: frontend-challenges/email-subscribe
