name: Deploy Product Preview Card Component to GH-Pages

on:
  push:
    branches:
      - master
    paths:
      - product-preview-card-component/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
         working-directory: product-preview-card-component

      - name: Build project - Product Preview Card Component
        run: npm --prefix product-preview-card-component run build

      - name: Upload build files
        uses: actions/upload-artifact@v2
        with:
          name: prod-files
          path: ./product-preview-card-component/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download Build artifacts
        uses: actions/download-artifact@v2
        with:
          name: prod-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./dist
          destination_dir: product-preview-card-component